const actionTypes = {
  LOADING: 'LOADING',
  LOADED: 'LOADED',
  SEARCH_SUCCESS: 'SEARCH_SUCCESS',
  SEARCH_API_ERRROR: 'SEARCH_API_ERROR',
  SEARCH_FAIL: 'SEARCH_FAIL',
  SEARCH_UPDATE_VALUE: 'SEARCH_UPDATE_VALUE',
  SEARCH_RESET: 'SEARCH_RESET',
  SET_CURRENT: 'SET_CURRENT'
};

export default actionTypes;
